void display_init();
bool does_support_partial_update();
void clear_screen();
void poweroff_display();
void end_display();

void helloWorld();
void printText(char text[]);
void helloWorldForDummies();
void helloFullScreenPartialMode();
void helloArduino();
void helloEpaper();
void stripeTest();
void helloStripe(uint16_t pw_xe);
void helloValue(double v, int digits);
void deepSleepTest();
void showBox(uint16_t x, uint16_t y, uint16_t w, uint16_t h, bool partial);
void drawCornerTest();
void showFont(const char name[], const char font_name[]);
void drawFont(const char name[], const char font_name[]);
void showPartialUpdate();
void drawGrid();
void drawBitmaps();
void drawGraphics();
